# Streamlit Secrets Configuration
# Add your API keys here for deployment

# Google Gemini API Key (required for fact-checking)
GEMINI_API_KEY = "AIzaSyAfEfoT5FrEf40ku8iprMMWIxEO89aK4BI"

# OpenAI API Key (if using OpenAI features)
OPENAI_API_KEY = "your_openai_api_key_here"

# Note: In Streamlit Cloud, add these secrets through the web interface
# Go to your app settings > Secrets and add the keys there
